channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=25.2
- pip:
  - mlflow==3.4.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.3.2
  - pyarrow==14.0.2
  - scikit-learn==1.7.1
  - scipy==1.15.3
name: mlflow-env
